In [1]:
import pandas as pd

In [2]:
df_prob = pd.read_csv('data/datos_con_probabilidad_impago.csv')
df_prob.head()

,ID,Edad,Ingresos,Monto_Inicial,Scoring_Crediticio,Meses_Empleo,Num_Creditos,Ratio_Interes,Duracion,Ratio_Deuda_Ingresos,...,Tipo_Jornada_Laboral_Jornada completa,Tipo_Jornada_Laboral_Tiempo parcial,Esfuerzo_Inicial_Fr,Esfuerzo_Inicial_Al,Ahorro_Intereses_Pct,Sobreesfuerzo_Inicial_Al,Ambos_Superan_Limite,Esfuerzo_Sistema_Elegido,Sistema_Recomendado_Francés,Probabilidad_Impago
0,KG9CT9,34,56572,73978,763,86,1,13.91,60,0.55,...,0,1,36.439698,44.343385,10.107178,372.606139,1,36.439698,1,0.618775
1,V5O0K9,37,68698,150000,824,162,2,10.53,24,0.37,...,1,0,121.549207,132.165420,3.238250,607.760466,1,121.549207,1,0.398983
2,YE5GD0,40,50000,7490,671,167,2,9.24,60,0.10,...,0,0,3.752495,4.380152,6.990729,26.152370,0,4.380152,0,0.451483
3,Q6HQ3D,38,63033,11801,649,196,1,7.63,48,0.10,...,0,1,5.445751,6.108969,4.723142,34.837147,0,6.108969,0,0.412336
4,XO8CO4,19,22301,40000,788,17,4,8.40,36,0.50,...,1,0,67.845326,74.854640,3.906059,130.262266,1,67.845326,1,0.569220

Leemos el dataset original y hacemos los cambios que hicimos en el preprocesamiento pero antes de codificar las variables para mantener las variables originales para el PowerBI

In [3]:
prestamos = pd.read_excel('data/Prestamos_Data_Alumnos_v5.xlsx')
prestamos.head()

,ID,Edad,Ingresos,Monto_Inicial,Scoring_Crediticio,Meses_Empleo,Num_Creditos,Ratio_Interes,Duracion,Ratio_Deuda_Ingresos,Estudios,Tipo_Jornada_Laboral,Estado_Civil,Posesion_Hipoteca,Personas_Cargo,Proposito,Fiador,Impago,Prima
0,O77MPJ,26,19153.0,6973,706,9.0,1,19.05,36.0,0.10,Grado Universitario,Jornada completa,Soltero,0.0,1.0,Automóvil,1.0,1,130.83
1,6B4H6E,22,16000.0,10000,769,22.0,1,8.96,48.0,0.32,Escolar,Desempleado,Soltero,1.0,1.0,Vivienda,0.0,0,65.85
2,VKTUXP,33,38308.0,16474,699,70.0,3,14.07,36.0,0.20,Máster,Jornada completa,Casado,1.0,1.0,Vivienda,0.0,0,260.60
3,5P9OVL,51,51271.0,40770,812,309.0,1,12.66,12.0,0.36,Grado Universitario,Jornada completa,Casado,0.0,1.0,Vivienda,1.0,0,221.02
4,KG9CT9,34,56572.0,73978,763,86.0,1,13.91,60.0,0.55,Máster,Tiempo parcial,Soltero,0.0,0.0,Educación,0.0,0,800.00

In [4]:
prestamos = prestamos[prestamos["Proposito"] == "Educación"].copy()

print("Dimensiones de la muestra:", prestamos.shape)

Dimensiones de la muestra: (178609, 19)

In [5]:
prestamos = prestamos.drop(columns=["Proposito"]) # la variable ya no aporta información nueva

In [6]:
# las columnas 'Posesion_Hipoteca', 'Personas_Cargo' y 'Fiador' están en float y hay que pasarlas a int porque son categorías binarias, es decir, es 0 o 1.
prestamos['Posesion_Hipoteca'] = prestamos['Posesion_Hipoteca'].astype(int)
prestamos['Personas_Cargo'] = prestamos['Personas_Cargo'].astype(int)
prestamos['Fiador'] = prestamos['Fiador'].astype(int)

In [7]:
# las columna 'Duracion' y 'Meses_Empleo' también hay que pasarla a int porque la duración está en meses, y no tiene decimales
prestamos['Duracion'] = prestamos['Duracion'].astype(int)
prestamos['Meses_Empleo'] = prestamos['Meses_Empleo'].astype(int)

In [8]:
# La columna 'Ingresos' también hay que ponerla en int porque no tiene decimales
prestamos['Ingresos'] = prestamos['Ingresos'].astype(int)

In [9]:
prestamos.isna().sum() # solo hay dos nulos en todo el dataset. El dataset es muy grande, por lo tanto, hemos decidido borrar las filas que contienen los nulos ya que el impacto de eliminarlas es muy pequeño.

ID                      0
Edad                    0
Ingresos                0
Monto_Inicial           0
Scoring_Crediticio      0
Meses_Empleo            0
Num_Creditos            0
Ratio_Interes           1
Duracion                0
Ratio_Deuda_Ingresos    0
Estudios                1
Tipo_Jornada_Laboral    0
Estado_Civil            0
Posesion_Hipoteca       0
Personas_Cargo          0
Fiador                  0
Impago                  0
Prima                   0
dtype: int64

In [10]:
prestamos = prestamos.dropna()

In [11]:
print("Número de filas:", len(prestamos))
print("Número de ID únicos:", prestamos["ID"].nunique())
print("ID duplicados:", prestamos["ID"].duplicated().sum())    # no hay ningún id duplicado, todos son únicos

Número de filas: 178607
Número de ID únicos: 178606
ID duplicados: 1

In [12]:
prestamos.duplicated().sum() # solo hay un duplicado, por lo que eliminamos la fila tambien

np.int64(1)

In [13]:
prestamos = prestamos.drop_duplicates()

In [14]:
# Guardamos el dataset
prestamos.to_csv(
    "docker_reto_5_alumnos/datos/datos_powerbi.csv",
    index=False
)